import type { Metadata } from 'next'

import { StackProvider, StackTheme } from '@stackframe/stack'
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import { ThemeProvider } from 'next-themes'
import { extractRouterConfig } from 'uploadthing/server'

import { Toaster } from '@orbitkit/ui/toast'

import { PostHogReactProvider } from '@/lib/posthog/react'
import { stackServerApp } from '@/lib/stack'

import { fileRouter } from './api/uploadthing/core'

import './globals.css'

import type { PropsWithChildren } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * The root layout of the entire application. This is where we wrap the entire application in the necessary providers.
 * @param props The props to the layout, which will be every page in this application.
 * @param props.children The children, which is the page the user is currently on.
 * @returns The layout of the application.
 */
export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en' dir='ltr' suppressHydrationWarning>
      <PostHogReactProvider>
        <body className={`${GeistSans.variable} ${GeistMono.variable}`}>
          <StackProvider app={stackServerApp}>
            <StackTheme>
              <NextSSRPlugin routerConfig={extractRouterConfig(fileRouter)} />
              <ThemeProvider
                attribute='class'
                enableSystem
                disableTransitionOnChange
              >
                <>{children}</>
                <Toaster />
              </ThemeProvider>
            </StackTheme>
          </StackProvider>
        </body>
      </PostHogReactProvider>
    </html>
  )
}
